# Generated by Django 5.0.4 on 2024-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location_alter_inventoryitem_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
